server:
  port : 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anhejy
    username: root
    password:
mybatis:
  mapper-locations: classpath:com/ctsi/*/mapper/*.xml